"""Format book deals as Telegram-friendly Markdown."""

from datetime import datetime, timezone
from typing import Any


def _format_book_entry(book: dict[str, Any]) -> str:
    """Format a single book with title prominent, details below."""
    price_str = f"${book['price']:.2f}" if book.get("price") is not None else "N/A"
    title = book.get("title", "Unknown Title")
    author = book.get("author", "")
    url = book.get("url", "")
    
    if len(title) > 80:
        title = title[:77] + "..."
    
    # Title: bold and prominent on its own line
    lines = [f"📕 *{title}*"]
    
    # Author: italic, smaller feel
    if author:
        lines.append(f"_{author}_")
    
    # Price + savings + link on one compact line
    details = f"💰 {price_str}"
    list_price = book.get("list_price")
    savings_pct = book.get("savings_pct")
    if list_price and savings_pct:
        details += f" ~~${list_price:.2f}~~ \\({savings_pct}% off\\)"
    elif list_price:
        details += f" ~~${list_price:.2f}~~"
    elif savings_pct:
        details += f" \\({savings_pct}% off\\)"
    # BookBub-style "limited time" flag (§6f): a real markdown (>=50% off the
    # ebook list price), not an everyday low price.
    if savings_pct is not None and savings_pct >= 50:
        details += " ⏳ limited time"
    elif book.get("list_source") == "history":
        # History-based price drop (t_d84465dd): the page exposed no digital
        # list price, so no savings % exists — the deal signal is a fresh
        # at-or-below-best price vs the 30-day history. Mark it as a drop
        # rather than an everyday cheap price.
        details += " 📉 price drop"
    if url:
        details += f"  🔗 [Link]({url})"
    lines.append(details)
    
    return "\n".join(lines)


def format_report(books: list[dict[str, Any]], new_count: int, 
                  dropped_count: int, region_warning: str | None = None) -> str:
    """Format the daily deals report with tracked authors section first."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    
    lines = [
        f"📚 *Kindle Non\\-Fiction Deals — {now}*",
        "",
    ]
    
    if not books:
        lines.append("No Fantasy or Sci\\-Fi deals found today\\.")
        lines.append("_Only books with a verified ebook\\-list discount are shown — "
                     "unverifiable list prices are never claimed\\._")
        lines.append("")
        lines.append(f"_📊 Stats: {new_count} new, {dropped_count} price drops today_")
        return "\n".join(lines)
    
    # Split into tracked authors vs others
    tracked = [b for b in books if b.get("tracked_author")]
    others = [b for b in books if not b.get("tracked_author")]
    
    lines.append(f"_{len(books)} deals found_ | 🆕 {new_count} new | 📉 {dropped_count} price drops")
    lines.append("")
    
    # Tracked authors section
    if tracked:
        lines.append("*⭐ Your Authors*")
        lines.append("")
        for book in tracked:
            lines.append(_format_book_entry(book))
            lines.append("")  # extra spacing between entries
        lines.append("")
    
    # All other deals section
    if others:
        lines.append("*📖 All Deals*")
        lines.append("")
        for book in others:
            lines.append(_format_book_entry(book))
            lines.append("")  # extra spacing between entries
        lines.append("")
    
    lines.append("")
    # Region warning (t_13047664): if the fetches resolved to a non-US
    # storefront, say so prominently — the prices are for THAT marketplace,
    # not the one the user's browser shows.
    if region_warning:
        lines.append(f"⚠️ *Region warning:* enrichment pages resolved to "
                     f"{region_warning} \\- prices are NOT the US storefront "
                     f"the bot targets\\.")
        lines.append("")
    # Region disclaimer (t_f893b2c1): prices are verified LIVE on the US
    # Amazon storefront at fetch time; Amazon serves region-specific prices,
    # so what the user's browser shows (EU/other) may differ.
    lines.append("_Prices verified live on the US Amazon storefront at fetch time \\- your region may show a different price\\._")
    lines.append("")
    lines.append("_🤖 Generated by Kindle Deals Bot_")
    
    # Cover images as MEDIA tags
    media_lines = []
    for book in books:
        cover_path = book.get("cover_path")
        if cover_path:
            media_lines.append(f"MEDIA:{cover_path}")
    
    if media_lines:
        lines.append("")
        lines.extend(media_lines)
    
    return "\n".join(lines)


def format_empty_report() -> str:
    """Report when no sources returned data at all."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        f"📚 *Kindle Non-Fiction Deals — {now}*\n\n"
        "⚠️ Could not fetch deals from any source today\\. "
        "Amazon may be blocking requests or the selectors need updating\\.\n\n"
        "_🤖 Generated by Kindle Deals Bot_"
    )
