"""Lightpanda fetcher — batch browser fetch via the Lightpanda CLI.

Replaces curl_cffi as the transport layer. Lightpanda runs headless
Chromium-free JS rendering in a single process, fetching all URLs in one
batch (~3s for 3 pages, ~5s for 10 product pages vs 25-30s with curl_cffi).

Requires: lightpanda binary on PATH or configured via config:
  scraping:
    lightpanda_bin: /home/stefan/.local/bin/lightpanda

Retry behavior: HTTP 429/5xx (Amazon/CloudFront rate-limits) and known
error-page bodies are RETRYABLE. fetch_all retries the failed URLs with
backoff (3 attempts, 5s/15s/30s ladder for rate-limits; short 2s delay for
anti-bot captcha/error-page bodies, where waiting doesn't help) before
reporting failure, so the FallbackFetcher only sees a fallback after
retries are exhausted.

NOTE (2026-08-14, t_f893b2c1): Lightpanda's User-Agent is "Lightpanda/1.0"
(+ Sec-CH-UA "Lightpanda") and --user-agent forbids impersonating browsers
(any value containing "Mozilla" is rejected), so Amazon's bot detection
fingerprints it and serves the validateCaptcha interstitial on ~75% of
PRODUCT-page requests. Product-page enrichment therefore bypasses Lightpanda
entirely (scraper.py uses curl_cffi chrome124 impersonation for product
pages). This fetcher remains the primary for LISTING pages (deal pages,
best sellers), where it is fast and usually clean.
"""

import json
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Any

from bs4 import BeautifulSoup


# US locale cookies injected into the jar (Amazon region detection)
US_COOKIES = [
    {"name": "session-id", "value": "130-0000000-0000000", "domain": ".amazon.com", "path": "/", "secure": False, "httpOnly": False},
    {"name": "ubid-main", "value": "130-0000000-0000000", "domain": ".amazon.com", "path": "/", "secure": False, "httpOnly": False},
    {"name": "lc-acbuk", "value": "en_US", "domain": ".amazon.com", "path": "/", "secure": False, "httpOnly": False},
    {"name": "i18n-prefs", "value": "USD", "domain": ".amazon.com", "path": "/", "secure": False, "httpOnly": False},
    {"name": "session-id-time", "value": "2082787201l", "domain": ".amazon.com", "path": "/", "secure": False, "httpOnly": False},
]

# HTTP statuses treated as retryable rate-limit / server errors
RETRYABLE_STATUSES = {429, 500, 502, 503, 504}

# Bodies of Amazon/CloudFront error pages (503 rate-limit, captcha, etc.).
# Only consulted when the page is small — real listing pages are much larger,
# so a false positive on a genuine 200 page is very unlikely. Each entry is
# (human-readable-name, regex): the name is used for failure reasons in
# last_failures and log lines (instead of a meaningless "HTTP 200").
ERROR_PAGE_PATTERNS = [
    ("cloudfront 503", re.compile(r"sorry!?\s+something went wrong", re.IGNORECASE)),
    ("request not satisfied", re.compile(r"request could not be satisfied", re.IGNORECASE)),
    ("cloudfront", re.compile(r"generated by cloudfront", re.IGNORECASE)),
    ("robot check", re.compile(r"robot check", re.IGNORECASE)),
    ("captcha (characters)", re.compile(r"enter the characters you see below", re.IGNORECASE)),
    ("service unavailable", re.compile(r"service unavailable", re.IGNORECASE)),
    ("try again later", re.compile(r"try again later", re.IGNORECASE)),
    ("rate limit", re.compile(r"rate limit", re.IGNORECASE)),
    ("access denied", re.compile(r"access denied", re.IGNORECASE)),
    # Amazon anti-bot interstitial: "Click the button below to continue
    # shopping" with a /errors_page/validateCaptcha form. Lightpanda can be
    # served this for product pages while deal pages succeed; without these
    # signatures the captcha page is cached as a VALID fetch, the curl_cffi
    # fallback never runs, and every book dies at enrichment with no price.
    ("captcha (validateCaptcha)", re.compile(r"validateCaptcha", re.IGNORECASE)),
    ("captcha (continue shopping)", re.compile(r"click the button below to continue shopping", re.IGNORECASE)),
]
_ERROR_PAGE_MAX_BYTES = 60_000


def _norm(u: str) -> str:
    """Lightpanda percent-encodes URLs (e.g. ':' -> '%3A'); match by decoded form."""
    from urllib.parse import unquote
    return unquote(u)


class LightpandaFetcher:
    """Fetches multiple URLs in one Lightpanda batch process, cache-aware."""

    def __init__(self, config: dict[str, Any]):
        self.scraping_cfg = config.get("scraping", {})
        self.bin = self.scraping_cfg.get(
            "lightpanda_bin", "/home/stefan/.local/bin/lightpanda"
        )
        self.wait_ms = self.scraping_cfg.get("lightpanda_wait_ms", 6000)
        self.cookie_path = Path(self.scraping_cfg.get(
            "lightpanda_cookies", "/tmp/lightpanda-cookies.json"
        ))
        self.max_attempts = int(self.scraping_cfg.get("lightpanda_retries", 3))
        self.retry_backoff = list(self.scraping_cfg.get(
            "lightpanda_retry_backoff", [5, 15, 30]
        ))
        # Per-URL failure dumps only when debug is on (config `scraping.debug`
        # or env KINDLE_DEBUG=1). Normal runs get one summarized line per batch.
        self.debug = bool(self.scraping_cfg.get("debug", False)) or bool(
            os.environ.get("KINDLE_DEBUG")
        )
        self._cache: dict[str, BeautifulSoup | None] = {}
        # url -> reason, populated by the last fetch_all (read by FallbackFetcher)
        self.last_failures: dict[str, str] = {}
        self._ensure_cookie_jar()

    def _ensure_cookie_jar(self) -> None:
        if self.cookie_path.exists():
            return
        self.cookie_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.cookie_path, "w") as f:
            json.dump(US_COOKIES, f, indent=1)

    @classmethod
    def _is_error_page(cls, status: int, content: str) -> bool:
        """True when the response is a retryable rate-limit / server error.

        Two signals: an explicit HTTP 429/5xx status, or (when the status is
        missing/200) a small page whose body matches a known Amazon/CloudFront
        error signature — Lightpanda sometimes reports the error page with a
        200/missing status, which used to slip through as a valid fetch.
        """
        if status in RETRYABLE_STATUSES:
            return True
        if status and not (200 <= status < 300):
            return False  # other client errors (404 etc.) — not retryable
        if len(content) > _ERROR_PAGE_MAX_BYTES:
            return False  # too big to be an error page; real content
        return any(pat.search(content) for _, pat in ERROR_PAGE_PATTERNS)

    @classmethod
    def _error_reason(cls, status: int, content: str) -> str:
        """Human-readable reason for a retryable failure (for logs + last_failures).

        e.g. "HTTP 503" for an explicit rate-limit status, or
        "captcha (continue shopping)" for a 200-status anti-bot interstitial —
        instead of a meaningless "HTTP 200".
        """
        if status in RETRYABLE_STATUSES:
            return f"HTTP {status}"
        for name, pat in ERROR_PAGE_PATTERNS:
            if pat.search(content):
                return name
        return "error page content"

    def _fetch_batch(self, urls: list[str]) -> dict[str, dict]:
        """Run one lightpanda batch for the given URLs.

        Returns {norm(url): raw result}. Empty dict on total batch failure
        (missing binary, crash, unparseable output).
        """
        if not urls:
            return {}
        cmd = [self.bin, "fetch", *urls, "--dump", "html",
               "--wait-ms", str(self.wait_ms),
               "--cookie", str(self.cookie_path),
               "--json"]
        try:
            proc = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        except (subprocess.TimeoutExpired, FileNotFoundError) as e:
            print(f"  [WARN] lightpanda batch failed: {e}", flush=True)
            return {}

        try:
            data = json.loads(proc.stdout)
        except json.JSONDecodeError:
            print(f"  [WARN] lightpanda bad output: {proc.stderr[:200]}", flush=True)
            return {}

        # Single URL → bare result object; multiple → {"results": [...]}
        if isinstance(data, dict) and "results" in data:
            results = data["results"]
        elif isinstance(data, list):
            results = data
        else:
            results = [data]

        out: dict[str, dict] = {}
        for r in results:
            if not isinstance(r, dict):
                continue
            url = r.get("url", "")
            if url:
                out[_norm(url)] = r
        return out

    def fetch_all(self, urls: list[str]) -> dict[str, BeautifulSoup | None]:
        """Fetch uncached URLs in one batch. Returns {url: soup} for all.

        Retryable failures (HTTP 429/5xx or error-page bodies) are retried
        with backoff up to self.max_attempts. URLs still failing afterwards
        are returned as None and recorded in self.last_failures (url -> reason)
        so the FallbackFetcher can log the 503 count before falling back.
        """
        missing = [u for u in urls if u not in self._cache]
        self.last_failures = {}
        if not missing:
            return dict(self._cache)

        pending = list(missing)
        retry_reasons: dict[str, str] = {}
        attempt = 0
        while pending and attempt < self.max_attempts:
            if attempt > 0:
                # Rate-limit/server-error failures (HTTP 429/5xx) need the
                # cool-down ladder. Anti-bot captcha/error-page bodies do NOT
                # (waiting doesn't clear them — each attempt is an independent
                # lottery), so retry those with a short fixed delay.
                reasons = [retry_reasons.get(u, "") for u in pending]
                needs_cooldown = any(r.startswith("HTTP ") for r in reasons)
                delay = (
                    self.retry_backoff[min(attempt - 1, len(self.retry_backoff) - 1)]
                    if needs_cooldown else 2
                )
                print(f"  [RETRY] lightpanda: {len(pending)} URL(s) failed, "
                      f"retry {attempt}/{self.max_attempts - 1} in {delay}s ...",
                      flush=True)
                time.sleep(delay)

            attempt += 1
            results_by_url = self._fetch_batch(pending)
            if not results_by_url:
                # Total batch failure (missing binary, crash, bad JSON) — fail
                # fast instead of pointlessly retrying an infra problem.
                for u in pending:
                    self._cache[u] = None
                    self.last_failures[u] = "lightpanda batch failed"
                pending = []
                break

            still_failed: list[str] = []
            for u in pending:
                r = results_by_url.get(_norm(u))
                if r is None:
                    retry_reasons[u] = "no result entry"
                    still_failed.append(u)
                    continue
                status = r.get("http_status", 0)
                content = r.get("content", "") or ""
                if self._is_error_page(status, content):
                    retry_reasons[u] = self._error_reason(status, content)
                    still_failed.append(u)
                elif (status in (0, 200)) and content:
                    self._cache[u] = BeautifulSoup(content, "lxml")
                else:
                    self._cache[u] = None
                    self.last_failures[u] = self._error_reason(status, content)
            pending = still_failed

        for u in pending:
            self._cache[u] = None
            self.last_failures[u] = retry_reasons.get(u, "retries exhausted")

        if self.last_failures:
            # One summarized line per batch (reason counts), per-URL details
            # only in debug mode — keeps normal cron output readable.
            counts: dict[str, int] = {}
            for reason in self.last_failures.values():
                counts[reason] = counts.get(reason, 0) + 1
            summary = ", ".join(
                f"{c}× {r}" for r, c in sorted(counts.items())
            )
            print(f"  [WARN] lightpanda failed {len(self.last_failures)} URL(s) "
                  f"after {self.max_attempts} attempt(s): {summary}", flush=True)
            if self.debug:
                for u, reason in self.last_failures.items():
                    print(f"    {reason}: {u}", flush=True)

        return dict(self._cache)
